modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/BinaryQuantumSoul/BinaryMod/issues"
license="GNU Affero General Public License"

[[mods]]
modId="binarymod"
version="${file.jarVersion}"
displayName="Binary Dimension"
# updateJSONURL="https://myurl.me"
displayURL="https://www.curseforge.com/minecraft/mc-mods/binary-dimension"
logoFile="logo.png"
credits="Windows, Java, The Matrix, WWW"
authors="QuantumSoul"
description='''
Explore the matrix, fight bugs and viruses, go to the dark web and craft machines
'''

[[dependencies.binarydimension]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.binarydimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
